src/carts/urls.py
from django.urls import path, re_path

from .views import cart_home, cart_update

# Check https://kirr.co/plqpin (or) https://www.codingforentrepreneurs.com/blog/common-regular-expressions-for-django-urls/ for reqex for django
urlpatterns = [
    path('', cart_home, name= 'home'),
    path('update', cart_update, name= 'update'),
] 

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import home_page,form_page, login_page, register_page

# Check https://kirr.co/plqpin (or) https://www.codingforentrepreneurs.com/blog/common-regular-expressions-for-django-urls/ for reqex for django
urlpatterns = [
    path('register/', register_page, name='register'),
    path('login/', login_page, name='login'),
    path('home/', home_page, name='home'),
    path('contact/', form_page, name='contact'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include(("products.urls", "products"), namespace="products")),
    path('search/', include(("search.urls", "search"), namespace="search")),
    path('cart/', include(("carts.urls", "carts"), namespace="cart")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     url_patterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     url_patterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path, re_path

from .views import ProductDetailSlugView,ProductDetailView,ProductFeaturedListView, ProductFeaturedDetailView, ProductListView, product_detail_view, product_list_view

# Check https://kirr.co/plqpin (or) https://www.codingforentrepreneurs.com/blog/common-regular-expressions-for-django-urls/ for reqex for django
urlpatterns = [
    path('', ProductListView.as_view(), name= 'list'),
    # path('products-fbv/', product_list_view),
    # re_path(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    # re_path(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    # path('products/featured/', ProductFeaturedListView.as_view()),
    # re_path(r'^products/featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
] 

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href='{% static "css/main.css" %}' />

src/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- Font-awesome -->
<script src="https://kit.fontawesome.com/feb2dae6e2.js" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'carts:home' as cart_url %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
  <div class='container'>
     <a class="navbar-brand" href="{% url 'home' %}">
        <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
      Bootstrap
     </a>
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>




     <div class='collapse navbar-collapse' id='navbarCollapseLinks'>
       <ul class='navbar-nav mr-auto'>
          <li class="nav-item {% if request.path == home_url %}active{% endif %}"> <!-- This if condition is to highlight on the navbar if we are on that page-->
            <a class="nav-link" aria-current="page" href="{{ home_url }}">Home</a>
          </li>
          <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
            <a class="nav-link" href="{{ contact_url }}">Contact</a>
          </li>
          <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
            <a class="nav-link" href="{{ product_list_url }}">Products</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
          {% else %}
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{{ login_url }}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a class="nav-link" href="{{cart_url}}"> 
              <i class="fas fa-shopping-cart" aria-hidden="true"></i>{{ request.session.cart_items }}
            </a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->
       </ul>
       {% include 'search/snippets/search_form.html'%}
     </div>
 </div>
</nav>